# Generated by Django 3.2.15 on 2022-10-12 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
        ('partidos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscripciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_inscripcion', models.DateTimeField()),
                ('fecha_hora_baja', models.DateTimeField()),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.perfil')),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partidos.partido')),
            ],
        ),
    ]
