# Generated by Django 3.2.15 on 2023-01-21 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0002_rename_inscripciones_inscripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcion',
            name='fecha_hora_baja',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
