# Generated by Django 3.2.15 on 2023-04-12 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0003_alter_inscripcion_fecha_hora_baja'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcion',
            name='notificado',
            field=models.BooleanField(default=False),
        ),
    ]
