# Generated by Django 3.2.15 on 2022-10-12 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
        ('canchas', '0001_initial'),
        ('tipos_partidos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('cant_jugadores', models.BigIntegerField()),
                ('cancha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canchas.cancha')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.perfil')),
                ('tipo_partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tipos_partidos.tipo_partido')),
            ],
        ),
    ]
