# Generated by Django 3.2.15 on 2023-04-12 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partidos', '0002_inscriptospartido'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='suspendido',
            field=models.BooleanField(default=False),
        ),
    ]
