# Generated by Django 3.2.15 on 2023-04-15 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partidos', '0003_partido_suspendido'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='partido_jugado',
            field=models.BooleanField(default=True),
        ),
    ]
