# Generated by Django 3.2.15 on 2023-04-15 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partidos', '0004_partido_partido_jugado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partido',
            old_name='partido_jugado',
            new_name='confirmado',
        ),
        migrations.AddField(
            model_name='partido',
            name='fecha_hora_confirmado',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='partido',
            name='fecha_hora_suspendido',
            field=models.DateTimeField(default=None),
        ),
    ]
