# Generated by Django 3.2.15 on 2023-04-15 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partidos', '0005_auto_20230415_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partido',
            name='fecha_hora_confirmado',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='partido',
            name='fecha_hora_suspendido',
            field=models.DateTimeField(null=True),
        ),
    ]
