# Generated by Django 3.2.15 on 2023-04-20 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('canchas', '0004_auto_20230419_2022'),
        ('partidos', '0006_auto_20230415_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partido',
            name='cancha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canchas.canchaprecio'),
        ),
    ]
