# Generated by Django 3.2.15 on 2023-04-11 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canchas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancha',
            name='abono_mensual',
            field=models.DecimalField(decimal_places=2, default=1500.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='cancha',
            name='valor_referi',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='cancha',
            name='valor_uso',
            field=models.DecimalField(decimal_places=2, default=1000.0, max_digits=6),
        ),
    ]
