# Generated by Django 3.2.15 on 2023-04-10 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canchas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancha',
            name='abono_mensual',
            field=models.DecimalField(decimal_places=2, default=1500, max_digits=5),
        ),
        migrations.AddField(
            model_name='cancha',
            name='valor_referi',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='cancha',
            name='valor_uso',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=5),
        ),
    ]
