# Generated by Django 3.2.15 on 2023-04-16 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canchas', '0002_auto_20230411_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancha',
            name='abono_mensual',
            field=models.DecimalField(decimal_places=2, default=1500.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cancha',
            name='valor_referi',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cancha',
            name='valor_uso',
            field=models.DecimalField(decimal_places=2, default=1000.0, max_digits=10),
        ),
    ]
