# Generated by Django 3.2.15 on 2023-04-11 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canchas', '0002_auto_20230410_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancha',
            name='valor_referi',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
    ]
