# Generated by Django 3.2.15 on 2023-04-19 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('canchas', '0003_auto_20230416_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cancha',
            name='abono_mensual',
        ),
        migrations.RemoveField(
            model_name='cancha',
            name='valor_referi',
        ),
        migrations.RemoveField(
            model_name='cancha',
            name='valor_uso',
        ),
        migrations.CreateModel(
            name='CanchaPrecio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_uso', models.DecimalField(decimal_places=2, default=1000.0, max_digits=10)),
                ('valor_referi', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('abono_mensual', models.DecimalField(decimal_places=2, default=1500.0, max_digits=10)),
                ('fecha', models.DateField(null=True)),
                ('cancha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canchas.cancha')),
            ],
        ),
    ]
