# Generated by Django 3.2.15 on 2023-04-11 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canchas', '0003_alter_cancha_valor_referi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancha',
            name='valor_referi',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
