# Generated by Django 3.2.15 on 2023-04-25 21:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canchas', '0004_auto_20230419_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancha',
            name='fecha_baja',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AddField(
            model_name='cancha',
            name='fecha_ingreso',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
    ]
