# Generated by Django 3.2.15 on 2023-04-25 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canchas', '0005_auto_20230425_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancha',
            name='fecha_baja',
            field=models.DateField(blank=True, null=True),
        ),
    ]
