# Generated by Django 3.2.15 on 2023-04-26 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('canchas', '0006_alter_cancha_fecha_baja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canchaprecio',
            name='cancha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='canchas.cancha'),
        ),
    ]
