# Generated by Django 3.2.15 on 2023-02-22 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partidos', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_invitacion', models.DateTimeField()),
                ('estado', models.CharField(blank=True, max_length=100, null=True)),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partidos.partido')),
                ('usuario_invita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitacion_requests_invita', to='usuarios.perfil')),
                ('usuario_invitado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitacion_requests_invitado', to='usuarios.perfil')),
            ],
        ),
    ]
