# Generated by Django 3.2.15 on 2023-04-19 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('canchas', '0004_auto_20230419_2022'),
        ('vouchers', '0002_alter_voucher_fecha_canje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='cancha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canchas.canchaprecio'),
        ),
    ]
