# Generated by Django 3.2.15 on 2023-04-21 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0003_alter_voucher_cancha'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='codigo',
            field=models.BigIntegerField(null=True),
        ),
    ]
